# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Install WiX
        run: dotnet tool install --global wix
      - name: Check path
        run: dir
      - name: Build WiX on Windows x86
        run: wix build D:\a\Installer_GasFlowControl\Installer_GasFlowControl\GasFlowControl\Package.wxs D:\a\Installer_GasFlowControl\Installer_GasFlowControl\GasFlowControl\Folders.wxs D:\a\Installer_GasFlowControl\Installer_GasFlowControl\GasFlowControl\Package.en-us.wxl D:\a\Installer_GasFlowControl\Installer_GasFlowControl\GasFlowControl\MainComponents.wxs -arch x86 -out D:\a\Installer_GasFlowControl\Installer_GasFlowControl\out\Setup_GasFlowControl_x86.msi
      - name: Build WiX on Windows x64
        run: wix build D:\a\Installer_GasFlowControl\Installer_GasFlowControl\GasFlowControl\Package.wxs D:\a\Installer_GasFlowControl\Installer_GasFlowControl\GasFlowControl\Folders.wxs D:\a\Installer_GasFlowControl\Installer_GasFlowControl\GasFlowControl\Package.en-us.wxl D:\a\Installer_GasFlowControl\Installer_GasFlowControl\GasFlowControl\MainComponents.wxs -arch x64 -out D:\a\Installer_GasFlowControl\Installer_GasFlowControl\out\Setup_GasFlowControl_x64.msi
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          # Artifact name
          name: "GasFlowControl-artifact"
          # A file, directory or wildcard pattern that describes what to upload
          path: .\out\*.msi
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error # optional, default is warn
          # Duration after which artifact will expire in days. 0 means using default retention.
     
         
                
      
